config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"


  devise_for :users,
             :path => '',
             :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => { :omniauth_callbacks => "omniauth_callbacks",
                               :registrations => 'registrations'}

  resources :users, only: :show
  resources :skill_tags, only: [:show, :create]
  resources :user_skills, only: [:create, :destroy]
  resources :plusings, only: [:create, :destroy]

end

app/models/adding.rb
class Adding < ApplicationRecord
  validates :user_id, presence: true
  validates :user_skill_id, presence: true
  belongs_to :user, dependent: :destroy
  belongs_to :user_skill, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plusing.rb
class Plusing < ApplicationRecord
  validates :user_id, presence: true
  validates :user_skill_id, presence: true
  validates :user_skill_id, uniqueness: { scope: :user_id,
    message: "2点以上の追加はできません。" }
  belongs_to :user
  belongs_to :user_skill
end

app/models/skill_tag.rb
class SkillTag < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  validates :name, uniqueness: { case_sensitive: false }
  has_many :user_skills, -> { order(points: :desc) }
  has_many :skilled_users, through: :user_skills, source: :user

  before_save :to_be_unique_name

  def to_be_unique_name
    self.name.strip
  end

  def skill_of(user)
    user_skills.find_by(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

validates :username, presence: true, length: {maximum: 50}

has_many :user_skills
has_many :skill_tags, through: :user_skills
has_many :plusings
has_many :addings


def self.from_omniauth(auth)
   user = User.where(:email => auth.info.email).first
   if user
     return user
   else
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.username = auth.info.name
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.image = auth.info.image
       user.password = Devise.friendly_token[0,20]
     end
   end
 end


 def plused?(user_skill)
   plusings.find_by(user_skill_id: user_skill.id)
 end

 def plus!(user_skill)
   plusings.create!(user_skill_id: user_skill.id)
 end

 def unplused!(user_skill)
   plusings.find_by(user_skill_id: user_skill.id).destroy
 end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  validates :user_id, presence: true
  validates :skill_tag_id, presence: true
  validates :skill_tag_id, uniqueness: { scope: :user_id,
    message: "同じスキルを２つ以上持つことはできません。" }
  validates :points, numericality: true
  belongs_to :user
  belongs_to :skill_tag
  has_many :plusings
  has_one :adding

  scope :points_desc, -> { order(points: :desc) }
  scope :created_desc, -> { order(created_at: :desc) }


  def first_10_plusing
    plusings.first(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @most_recently_added_skill = UserSkill.created_desc.first
    @highest_points_skill = UserSkill.points_desc.first
    @user_most_number_of_skills = User.find(UserSkill.group(:user_id).order("count_all desc").count.first.first)
    @number_of_skills = UserSkill.group(:user_id).order("count_all desc").count.first.second
  end
end

app/controllers/plusings_controller.rb
class PlusingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user_skill = UserSkill.find(params[:user_skill_id])
    current_user.plus!(@user_skill)
    @user_skill.increment!(:points)
  end

  def destroy
    @user_skill = Plusing.find(params[:id]).user_skill
    current_user.unplused!(@user_skill)
    @user_skill.decrement!(:points)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/skill_tags_controller.rb
class SkillTagsController < ApplicationController
  before_action :authenticate_user!

  def show
    @skill_tag = SkillTag.find(params[:id])
    @users = @skill_tag.skilled_users
  end

  def create
    @skill_tag = SkillTag.find_or_create_by(name: skill_tags_params[:name])
    if @skill_tag
      @user_skill = UserSkill.find_or_create_by(user_id: params[:skill_tag][:user_id], skill_tag_id: @skill_tag.id)
      Adding.find_or_create_by(user_id: params[:skill_tag][:added_user_id], user_skill_id: @user_skill.id)
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
      end
    end
  end


  private
  def skill_tags_params
    params.require(:skill_tag).permit(:name)
  end
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController

  def create

  end

  def delete
    #code
  end

  private
  def user_skills_params
    params.reqire(:user_skill).permit(:user_id, :skill_tag_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @user_skills = @user.user_skills.points_desc
    @feature_skills = @user_skills.first(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_picture(user)
    if user.image
      user.image
    else
      'https://ukla.org/images/icons/user-icon.svg'
    end
  end


 def alert_class_for(flash_type)
  {
    :success => 'alert-success',
    :error => 'alert-danger',
    :alert => 'alert-warning',
    :notice => 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plusings_helper.rb
module PlusingsHelper
end

app/helpers/skill_tags_helper.rb
module SkillTagsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skills</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <%= render 'shared/navbar' %>
    <%= render partial: "shared/flash_messages", flash: flash %>
  </header>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<br>
<br>
<br>
<h1 class="center">Share your skills!</h1>
<br>
<br>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="center">Most recently added skill!</h4>
      </div>
        <div class="panel-body">
          <div class="med_font center">
            <% if @most_recently_added_skill %>
              <%= link_to skill_tag_path(@most_recently_added_skill.skill_tag) do %>
                <%= @most_recently_added_skill.skill_tag.name %>
              <% end %>
              <%= link_to user_path(@most_recently_added_skill.user) do %>
                <%= image_tag user_picture(@most_recently_added_skill.user), class: "img-circle pic-small" %>
                <%= @most_recently_added_skill.user.username  %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="center">User having most number of skills!</h4>
        </div>
          <div class="panel-body">
            <div class="med_font center">
              <% if @highest_points_skill %>
                <%= "#{@number_of_skills} skills!" %>
                <%= link_to user_path(@user_most_number_of_skills) do %>
                  <%= image_tag user_picture(@user_most_number_of_skills), class: "img-circle pic-small" %>
                  <%= @user_most_number_of_skills.username %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="center">Highest points of skill!</h4>
          </div>
            <div class="panel-body">
              <div class="med_font center">
                <% if @user_most_number_of_skills %>
                  <%= "#{@highest_points_skill.points}" %>
                  <%= link_to skill_tag_path(@highest_points_skill.skill_tag) do %>
                    <%= @highest_points_skill.skill_tag.name %>
                  <% end %>
                  <%= link_to user_path(@highest_points_skill.user) do %>
                    <%= image_tag user_picture(@highest_points_skill.user), class: "img-circle pic-small" %>
                    <%= @highest_points_skill.user.username  %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
  </div>

app/views/plusings/_points_btn.html.erb
<% if current_user.plused?(user_skill) %>
  <%= link_to plusing_path(current_user.plused?(user_skill)), remote: true, method: :delete do %>
    <i class="fa fa-minus" aria-hidden="true"></i>
  <% end %>
<% else %>
  <%= link_to plusings_path(user_id: current_user.id, user_skill_id: user_skill.id), remote: true, method: :post do %>
    <i class="fa fa-plus" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/plusings/create.js.erb
$(".skill_<%= @user_skill.id %>_btn").html('<%= escape_javascript(render("plusings/points_btn", user_skill: @user_skill)) %>');
$(".skill_points_<%= @user_skill.id %>").text('<%= @user_skill.points %>');
$(".skill_<%= @user_skill.id %>_plused_users").append('<%= image_tag "#{user_picture(current_user)}", class: "img-circle pic-small img_#{current_user.id}"%>');

app/views/plusings/destroy.js.erb
$(".skill_<%= @user_skill.id %>_btn").html('<%= escape_javascript(render("plusings/points_btn", user_skill: @user_skill)) %>');
$(".skill_points_<%= @user_skill.id %>").text('<%= @user_skill.points %>');
$(".skill_<%= @user_skill.id %>_plused_users").children().last().remove();

app/views/shared/_flash_messages.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert <%= alert_class_for(flash_type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Skills", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li><%= link_to "Your Page", user_path(current_user) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag user_picture(current_user), class: "img-circle pic-small" %>&nbsp;
            <%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/skill_tags/_form.html.erb
<%= form_for SkillTag.new, url: skill_tags_path do |f| %>
  <div class="form-group inline_block">
    <%= f.text_field :name, placeholder: "skill name", class: "form-control inline_block" %>
  </div>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :added_user_id, value: current_user.id %>

  <div class="actions inline_block">
    <%= f.submit "追加", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/skill_tags/show.html.erb
<h1><%= @skill_tag.name %></h1>

<div class="row">
  <%= render @users, skill_tag: @skill_tag %>
</div>

app/views/user_skills/_user_skill.html.erb
<li id="skill-<%= user_skill.id %>">
  <div class="user_skills">
    <span class="points_span">
      <span class="skill_points_<%= user_skill.id %> points">
        <%= user_skill.points %>
      </span>
      <% unless  current_user == @user  %>
        <span class="skill_<%= user_skill.id %>_btn">
          <%= render 'plusings/points_btn', user_skill: user_skill %>
        </span>
      <% end %>
    </span>
    <span class="user_skill_name">
      <%= link_to "#{user_skill.skill_tag.name}", skill_tag_path(user_skill.skill_tag) %>
    </span>
    <% if @feature_skills.include?(user_skill) %>
      <span class="skill_<%= user_skill.id %>_plused_users">
        <% user_skill.first_10_plusing.each do |p| %>
          <%= image_tag "#{user_picture(p.user)}", class: "img-circle pic-small img_#{p.user.id}" %>
        <% end %>
      </span>
    <% end %>
  </div>
</li>

app/views/users/_user.html.erb
<div class="">
  <span class="pic_name">
    <%= link_to user_path(user) do %>
      <%= image_tag user_picture(user), class: "img-circle pic-small" %>
      <%= user.username %>
    <% end %>
  </span>
  <span class="points">
    <%= "#{@skill_tag.skill_of(user).points}" %>
  </span>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-12">
    <div class="user_top">
      <div class="avatar inline-block">
        <%= image_tag user_picture(@user), class: "img-circle pic-middle" %>
        <strong class="user_name"><%= @user.username%></strong>
      </div>
    </div>

    <h4 class="center"><%= "#{@user.username}"%> Skills</h4>
    <div class="skill_form center">
      <%= render "skill_tags/form", user: @user　%>
    </div>
    <ul class="skills">
    <% if @user_skills.any? %>
      <%= render @user_skills, user: @user %>
    <% else %>
      <br>
      <p class="center">you haven't added any skills yet.</p>
    <% end %>
  </div>
</div>